### ISSUE TITLE
stop running ANMultiAdRequest

### ISSUE THREAD

**Issue by maxacmaxac** [appnexus/mobile-sdk-android#58]
please create functionality to stop already running ANMultiAdRequest

in `load` function there is already functionality that is doing that.
this.mAdFetcher.stop();
this.mAdFetcher.clearDurations();

**Comment by avohraa** [comment]
This has been addressed in the latest release - https://github.com/appnexus/mobile-sdk-android/releases/tag/7.15

Closing it out. Feel free to reopen in case of an issue.

**Comment by maxacmaxac** [comment]
Problem still exist. 
Handler is not sopped, even is Fetcher stopped by this.mAdFetcher.stop();

E/AndroidRuntime: FATAL EXCEPTION: ANBackgroundThread
    Process: at.willhaben.debug, PID: 16609
    java.lang.NullPointerException: Attempt to invoke interface method 'com.appnexus.opensdk.MediaType com.appnexus.opensdk.Ad.getMediaType()' on a null object reference
        at com.appnexus.opensdk.AdFetcher$RequestHandler.handleMessage(AdFetcher.java:261)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
        
This will happen if I try to reuse ANMultiAdRequest
 if (ANMultiAdRequest.isMARRequestInProgress) {
                ANMultiAdRequest.stop()
                oldAdsList.forEach {
                    ANMultiAdRequest.removeAdUnit(it)
                }
}

newAdsList.forEach {
    ANMultiAdRequest.addAdUnit(it)
 }
oldAdsList = newAdsList
ANMultiAdRequest.load()

**Comment by avohraa** [comment]
Hi @maxacmaxac, we found few issues with the `MAR.stop()` implementation (`isMARRequestInProgress` boolean was not being set to the right state) and we will be fixing it in the next release.

We followed the steps provided above to replicate the crash, but couldn't reproduce the crash. Could you provide us with a sample app, reproducing the crash, so that we are sure the issue is fixed for you.

**Comment by avohraa** [comment]
Hi @maxacmaxac,

We have updated `MAR.stop()` in the latest release - https://github.com/appnexus/mobile-sdk-android/releases/tag/7.16

**Comment by avohraa** [comment]
Closing due to inactivity on this issue. Feel free to reopen if that arises again.
